// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuy1ssI17_Xa1pQPJImLK62Y8MdNJE9IE',
    appId: '1:1082598455865:web:19f40e63dae7665f8e6be8',
    messagingSenderId: '1082598455865',
    projectId: 'ibrahem-portfolio',
    authDomain: 'ibrahem-portfolio.firebaseapp.com',
    storageBucket: 'ibrahem-portfolio.firebasestorage.app',
    measurementId: 'G-0SCQD0EE82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIPzaXTioEdHQ_PeKks4hOR3t9v1eP3oE',
    appId: '1:1082598455865:android:d8bd184bae54939b8e6be8',
    messagingSenderId: '1082598455865',
    projectId: 'ibrahem-portfolio',
    storageBucket: 'ibrahem-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXt6acjwZjr1auMUVywkNn-Xig7ZgbTQg',
    appId: '1:1082598455865:ios:518f0a0b7b9f41978e6be8',
    messagingSenderId: '1082598455865',
    projectId: 'ibrahem-portfolio',
    storageBucket: 'ibrahem-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.ibrahemPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXt6acjwZjr1auMUVywkNn-Xig7ZgbTQg',
    appId: '1:1082598455865:ios:518f0a0b7b9f41978e6be8',
    messagingSenderId: '1082598455865',
    projectId: 'ibrahem-portfolio',
    storageBucket: 'ibrahem-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.ibrahemPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuy1ssI17_Xa1pQPJImLK62Y8MdNJE9IE',
    appId: '1:1082598455865:web:d9e0b79b5f409c7d8e6be8',
    messagingSenderId: '1082598455865',
    projectId: 'ibrahem-portfolio',
    authDomain: 'ibrahem-portfolio.firebaseapp.com',
    storageBucket: 'ibrahem-portfolio.firebasestorage.app',
    measurementId: 'G-D8C8YD6FW3',
  );
}
